package ec.tienda.movil.almacen.modelo;
// Generated 09/11/2017 16:57:53 by Hibernate Tools 4.3.1



/**
 * DetalleProducto generated by hbm2java
 */
public class DetalleProducto  implements java.io.Serializable {


     private Integer idDetalleProducto;
     private Producto producto;
     private String informacionEnvio;

    public DetalleProducto() {
    }

	
    public DetalleProducto(Producto producto) {
        this.producto = producto;
    }
    public DetalleProducto(Producto producto, String informacionEnvio) {
       this.producto = producto;
       this.informacionEnvio = informacionEnvio;
    }
   
    public Integer getIdDetalleProducto() {
        return this.idDetalleProducto;
    }
    
    public void setIdDetalleProducto(Integer idDetalleProducto) {
        this.idDetalleProducto = idDetalleProducto;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getInformacionEnvio() {
        return this.informacionEnvio;
    }
    
    public void setInformacionEnvio(String informacionEnvio) {
        this.informacionEnvio = informacionEnvio;
    }




}


