package ec.tienda.movil.almacen.modelo;
// Generated 09/11/2017 16:57:53 by Hibernate Tools 4.3.1



/**
 * ImagenProducto generated by hbm2java
 */
public class ImagenProducto  implements java.io.Serializable {


     private Integer idImagen;
     private Producto producto;
     private String directorio;
     private String nombre;

    public ImagenProducto() {
    }

	
    public ImagenProducto(Producto producto) {
        this.producto = producto;
    }
    public ImagenProducto(Producto producto, String directorio, String nombre) {
       this.producto = producto;
       this.directorio = directorio;
       this.nombre = nombre;
    }
   
    public Integer getIdImagen() {
        return this.idImagen;
    }
    
    public void setIdImagen(Integer idImagen) {
        this.idImagen = idImagen;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getDirectorio() {
        return this.directorio;
    }
    
    public void setDirectorio(String directorio) {
        this.directorio = directorio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


