package ec.tienda.movil.almacen.modelo;
// Generated 09/11/2017 16:57:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Motorizado generated by hbm2java
 */
public class Motorizado  implements java.io.Serializable {


     private Integer idMotorizado;
     private String identificacion;
     private Set salidas = new HashSet(0);

    public Motorizado() {
    }

    public Motorizado(String identificacion, Set salidas) {
       this.identificacion = identificacion;
       this.salidas = salidas;
    }
   
    public Integer getIdMotorizado() {
        return this.idMotorizado;
    }
    
    public void setIdMotorizado(Integer idMotorizado) {
        this.idMotorizado = idMotorizado;
    }
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }
    public Set getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set salidas) {
        this.salidas = salidas;
    }




}


