package ec.tienda.movil.almacen.modelo;
// Generated 09/11/2017 16:57:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idProducto;
     private Bodega bodega;
     private Subcategoria subcategoria;
     private String nombre;
     private String descripcion;
     private String codigo;
     private Set inventarios = new HashSet(0);
     private Set detalleProductos = new HashSet(0);
     private Set entradas = new HashSet(0);
     private Set reseniaProductos = new HashSet(0);
     private Set imagenProductos = new HashSet(0);
     private Set salidas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Bodega bodega, Subcategoria subcategoria) {
        this.bodega = bodega;
        this.subcategoria = subcategoria;
    }
    public Producto(Bodega bodega, Subcategoria subcategoria, String nombre, String descripcion, String codigo, Set inventarios, Set detalleProductos, Set entradas, Set reseniaProductos, Set imagenProductos, Set salidas) {
       this.bodega = bodega;
       this.subcategoria = subcategoria;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.codigo = codigo;
       this.inventarios = inventarios;
       this.detalleProductos = detalleProductos;
       this.entradas = entradas;
       this.reseniaProductos = reseniaProductos;
       this.imagenProductos = imagenProductos;
       this.salidas = salidas;
    }
   
    public Integer getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(Integer idProducto) {
        this.idProducto = idProducto;
    }
    public Bodega getBodega() {
        return this.bodega;
    }
    
    public void setBodega(Bodega bodega) {
        this.bodega = bodega;
    }
    public Subcategoria getSubcategoria() {
        return this.subcategoria;
    }
    
    public void setSubcategoria(Subcategoria subcategoria) {
        this.subcategoria = subcategoria;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set getInventarios() {
        return this.inventarios;
    }
    
    public void setInventarios(Set inventarios) {
        this.inventarios = inventarios;
    }
    public Set getDetalleProductos() {
        return this.detalleProductos;
    }
    
    public void setDetalleProductos(Set detalleProductos) {
        this.detalleProductos = detalleProductos;
    }
    public Set getEntradas() {
        return this.entradas;
    }
    
    public void setEntradas(Set entradas) {
        this.entradas = entradas;
    }
    public Set getReseniaProductos() {
        return this.reseniaProductos;
    }
    
    public void setReseniaProductos(Set reseniaProductos) {
        this.reseniaProductos = reseniaProductos;
    }
    public Set getImagenProductos() {
        return this.imagenProductos;
    }
    
    public void setImagenProductos(Set imagenProductos) {
        this.imagenProductos = imagenProductos;
    }
    public Set getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set salidas) {
        this.salidas = salidas;
    }




}


