package ec.tienda.movil.almacen.modelo;
// Generated 09/11/2017 16:57:53 by Hibernate Tools 4.3.1



/**
 * ReseniaProducto generated by hbm2java
 */
public class ReseniaProducto  implements java.io.Serializable {


     private Integer idReseniaProducto;
     private Producto producto;
     private String calificacion;
     private String opinion;
     private String identificacionCliente;

    public ReseniaProducto() {
    }

	
    public ReseniaProducto(Producto producto) {
        this.producto = producto;
    }
    public ReseniaProducto(Producto producto, String calificacion, String opinion, String identificacionCliente) {
       this.producto = producto;
       this.calificacion = calificacion;
       this.opinion = opinion;
       this.identificacionCliente = identificacionCliente;
    }
   
    public Integer getIdReseniaProducto() {
        return this.idReseniaProducto;
    }
    
    public void setIdReseniaProducto(Integer idReseniaProducto) {
        this.idReseniaProducto = idReseniaProducto;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(String calificacion) {
        this.calificacion = calificacion;
    }
    public String getOpinion() {
        return this.opinion;
    }
    
    public void setOpinion(String opinion) {
        this.opinion = opinion;
    }
    public String getIdentificacionCliente() {
        return this.identificacionCliente;
    }
    
    public void setIdentificacionCliente(String identificacionCliente) {
        this.identificacionCliente = identificacionCliente;
    }




}


