package ec.tienda.movil.almacen.modelo;
// Generated 09/11/2017 16:57:53 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Salida generated by hbm2java
 */
public class Salida  implements java.io.Serializable {


     private Integer idSalida;
     private Cliente cliente;
     private Motorizado motorizado;
     private Producto producto;
     private TipoEstado tipoEstado;
     private String unidad;
     private Date fecha;
     private String precioUnidad;
     private String precioSalida;

    public Salida() {
    }

	
    public Salida(Cliente cliente, Motorizado motorizado, Producto producto, TipoEstado tipoEstado) {
        this.cliente = cliente;
        this.motorizado = motorizado;
        this.producto = producto;
        this.tipoEstado = tipoEstado;
    }
    public Salida(Cliente cliente, Motorizado motorizado, Producto producto, TipoEstado tipoEstado, String unidad, Date fecha, String precioUnidad, String precioSalida) {
       this.cliente = cliente;
       this.motorizado = motorizado;
       this.producto = producto;
       this.tipoEstado = tipoEstado;
       this.unidad = unidad;
       this.fecha = fecha;
       this.precioUnidad = precioUnidad;
       this.precioSalida = precioSalida;
    }
   
    public Integer getIdSalida() {
        return this.idSalida;
    }
    
    public void setIdSalida(Integer idSalida) {
        this.idSalida = idSalida;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Motorizado getMotorizado() {
        return this.motorizado;
    }
    
    public void setMotorizado(Motorizado motorizado) {
        this.motorizado = motorizado;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public TipoEstado getTipoEstado() {
        return this.tipoEstado;
    }
    
    public void setTipoEstado(TipoEstado tipoEstado) {
        this.tipoEstado = tipoEstado;
    }
    public String getUnidad() {
        return this.unidad;
    }
    
    public void setUnidad(String unidad) {
        this.unidad = unidad;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getPrecioUnidad() {
        return this.precioUnidad;
    }
    
    public void setPrecioUnidad(String precioUnidad) {
        this.precioUnidad = precioUnidad;
    }
    public String getPrecioSalida() {
        return this.precioSalida;
    }
    
    public void setPrecioSalida(String precioSalida) {
        this.precioSalida = precioSalida;
    }




}


