package ec.tienda.movil.almacen.modelo;
// Generated 09/11/2017 16:57:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subcategoria generated by hbm2java
 */
public class Subcategoria  implements java.io.Serializable {


     private Integer idSubcategoria;
     private Categoria categoria;
     private String nombreSubcategoria;
     private Set productos = new HashSet(0);

    public Subcategoria() {
    }

	
    public Subcategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Subcategoria(Categoria categoria, String nombreSubcategoria, Set productos) {
       this.categoria = categoria;
       this.nombreSubcategoria = nombreSubcategoria;
       this.productos = productos;
    }
   
    public Integer getIdSubcategoria() {
        return this.idSubcategoria;
    }
    
    public void setIdSubcategoria(Integer idSubcategoria) {
        this.idSubcategoria = idSubcategoria;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNombreSubcategoria() {
        return this.nombreSubcategoria;
    }
    
    public void setNombreSubcategoria(String nombreSubcategoria) {
        this.nombreSubcategoria = nombreSubcategoria;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


