package ec.tienda.movil.almacen.modelo;
// Generated 09/11/2017 16:57:53 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoEstado generated by hbm2java
 */
public class TipoEstado  implements java.io.Serializable {


     private Integer idEstadoEnvio;
     private String estadoEnvio;
     private Set salidas = new HashSet(0);

    public TipoEstado() {
    }

    public TipoEstado(String estadoEnvio, Set salidas) {
       this.estadoEnvio = estadoEnvio;
       this.salidas = salidas;
    }
   
    public Integer getIdEstadoEnvio() {
        return this.idEstadoEnvio;
    }
    
    public void setIdEstadoEnvio(Integer idEstadoEnvio) {
        this.idEstadoEnvio = idEstadoEnvio;
    }
    public String getEstadoEnvio() {
        return this.estadoEnvio;
    }
    
    public void setEstadoEnvio(String estadoEnvio) {
        this.estadoEnvio = estadoEnvio;
    }
    public Set getSalidas() {
        return this.salidas;
    }
    
    public void setSalidas(Set salidas) {
        this.salidas = salidas;
    }




}


