package ec.tienda.movil.usuario.modelo;
// Generated 09/11/2017 16:19:18 by Hibernate Tools 4.3.1



/**
 * AsignacionPantalla generated by hbm2java
 */
public class AsignacionPantalla  implements java.io.Serializable {


     private Integer idAsignacionPantalla;
     private Pantalla pantalla;
     private Perfil perfil;

    public AsignacionPantalla() {
    }

    public AsignacionPantalla(Pantalla pantalla, Perfil perfil) {
       this.pantalla = pantalla;
       this.perfil = perfil;
    }
   
    public Integer getIdAsignacionPantalla() {
        return this.idAsignacionPantalla;
    }
    
    public void setIdAsignacionPantalla(Integer idAsignacionPantalla) {
        this.idAsignacionPantalla = idAsignacionPantalla;
    }
    public Pantalla getPantalla() {
        return this.pantalla;
    }
    
    public void setPantalla(Pantalla pantalla) {
        this.pantalla = pantalla;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }




}


