package ec.tienda.movil.usuario.modelo;
// Generated 09/11/2017 16:19:18 by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * AsignacionPerfil generated by hbm2java
 */
@XmlRootElement
public class AsignacionPerfil implements java.io.Serializable {

    private Integer idAsignacionPerfil;
    private DatosUsuario datosUsuario;
    private Perfil perfil;

    public AsignacionPerfil() {
    }

    public AsignacionPerfil(DatosUsuario datosUsuario, Perfil perfil) {
        this.datosUsuario = datosUsuario;
        this.perfil = perfil;
    }

    public Integer getIdAsignacionPerfil() {
        return this.idAsignacionPerfil;
    }

    public void setIdAsignacionPerfil(Integer idAsignacionPerfil) {
        this.idAsignacionPerfil = idAsignacionPerfil;
    }

    public DatosUsuario getDatosUsuario() {
        return this.datosUsuario;
    }

    public void setDatosUsuario(DatosUsuario datosUsuario) {
        this.datosUsuario = datosUsuario;
    }

    public Perfil getPerfil() {
        return this.perfil;
    }

    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }

}
