package ec.tienda.movil.usuario.modelo;
// Generated 09/11/2017 16:19:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * DatosUsuario generated by hbm2java
 */
@XmlRootElement
public class DatosUsuario implements java.io.Serializable {

    private Integer idContacto;
    private LoginUsuario loginUsuario;
    private TipoAcceso tipoAcceso;
    private TipoUsuario tipoUsuario;
    private String identificacion;
    private String nombres;
    private String apellidos;
    private String razonSocial;
    private String email;
    private String telefono;
    private String codigoPostal;
    private Set ubicacions = new HashSet(0);
    private Set asignacionPerfils = new HashSet(0);

    public DatosUsuario() {
    }

    public DatosUsuario(LoginUsuario loginUsuario, TipoAcceso tipoAcceso, TipoUsuario tipoUsuario, String email) {
        this.loginUsuario = loginUsuario;
        this.tipoAcceso = tipoAcceso;
        this.tipoUsuario = tipoUsuario;
        this.email = email;
    }

    public DatosUsuario(LoginUsuario loginUsuario, TipoAcceso tipoAcceso, TipoUsuario tipoUsuario, String identificacion, String nombres, String apellidos, String razonSocial, String email, String telefono, String codigoPostal, Set ubicacions, Set asignacionPerfils) {
        this.loginUsuario = loginUsuario;
        this.tipoAcceso = tipoAcceso;
        this.tipoUsuario = tipoUsuario;
        this.identificacion = identificacion;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.razonSocial = razonSocial;
        this.email = email;
        this.telefono = telefono;
        this.codigoPostal = codigoPostal;
        this.ubicacions = ubicacions;
        this.asignacionPerfils = asignacionPerfils;
    }

    public Integer getIdContacto() {
        return this.idContacto;
    }

    public void setIdContacto(Integer idContacto) {
        this.idContacto = idContacto;
    }

    public LoginUsuario getLoginUsuario() {
        return this.loginUsuario;
    }

    public void setLoginUsuario(LoginUsuario loginUsuario) {
        this.loginUsuario = loginUsuario;
    }

    public TipoAcceso getTipoAcceso() {
        return this.tipoAcceso;
    }

    public void setTipoAcceso(TipoAcceso tipoAcceso) {
        this.tipoAcceso = tipoAcceso;
    }

    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }

    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }

    public String getIdentificacion() {
        return this.identificacion;
    }

    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    public String getNombres() {
        return this.nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getApellidos() {
        return this.apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getRazonSocial() {
        return this.razonSocial;
    }

    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTelefono() {
        return this.telefono;
    }

    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    public String getCodigoPostal() {
        return this.codigoPostal;
    }

    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    public Set getUbicacions() {
        return this.ubicacions;
    }

    public void setUbicacions(Set ubicacions) {
        this.ubicacions = ubicacions;
    }

    public Set getAsignacionPerfils() {
        return this.asignacionPerfils;
    }

    public void setAsignacionPerfils(Set asignacionPerfils) {
        this.asignacionPerfils = asignacionPerfils;
    }

}
