package ec.tienda.movil.usuario.modelo;
// Generated 09/11/2017 16:19:18 by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * LoginUsuario generated by hbm2java
 */
@XmlRootElement
public class LoginUsuario implements java.io.Serializable {

    private Integer idUsuario;
    private String usuario;
    private String clave;
    private String estado;
    private DatosUsuario datosUsuario;

    public LoginUsuario() {
    }

    public LoginUsuario(String usuario, String clave) {
        this.usuario = usuario;
        this.clave = clave;
    }

    public LoginUsuario(String usuario, String clave, String estado, DatosUsuario datosUsuario) {
        this.usuario = usuario;
        this.clave = clave;
        this.estado = estado;
        this.datosUsuario = datosUsuario;
    }

    public Integer getIdUsuario() {
        return this.idUsuario;
    }

    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getClave() {
        return this.clave;
    }

    public void setClave(String clave) {
        this.clave = clave;
    }

    public String getEstado() {
        return this.estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public DatosUsuario getDatosUsuario() {
        return this.datosUsuario;
    }

    public void setDatosUsuario(DatosUsuario datosUsuario) {
        this.datosUsuario = datosUsuario;
    }

}
