package ec.tienda.movil.usuario.modelo;
// Generated 09/11/2017 16:19:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Pantalla generated by hbm2java
 */
public class Pantalla  implements java.io.Serializable {


     private Integer idPantalla;
     private String nombre;
     private String direccion;
     private Integer padre;
     private Boolean inicial;
     private Boolean primaria;
     private String idioma;
     private Set asignacionPantallas = new HashSet(0);

    public Pantalla() {
    }

	
    public Pantalla(String nombre, String direccion, String idioma) {
        this.nombre = nombre;
        this.direccion = direccion;
        this.idioma = idioma;
    }
    public Pantalla(String nombre, String direccion, Integer padre, Boolean inicial, Boolean primaria, String idioma, Set asignacionPantallas) {
       this.nombre = nombre;
       this.direccion = direccion;
       this.padre = padre;
       this.inicial = inicial;
       this.primaria = primaria;
       this.idioma = idioma;
       this.asignacionPantallas = asignacionPantallas;
    }
   
    public Integer getIdPantalla() {
        return this.idPantalla;
    }
    
    public void setIdPantalla(Integer idPantalla) {
        this.idPantalla = idPantalla;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getPadre() {
        return this.padre;
    }
    
    public void setPadre(Integer padre) {
        this.padre = padre;
    }
    public Boolean getInicial() {
        return this.inicial;
    }
    
    public void setInicial(Boolean inicial) {
        this.inicial = inicial;
    }
    public Boolean getPrimaria() {
        return this.primaria;
    }
    
    public void setPrimaria(Boolean primaria) {
        this.primaria = primaria;
    }
    public String getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(String idioma) {
        this.idioma = idioma;
    }
    public Set getAsignacionPantallas() {
        return this.asignacionPantallas;
    }
    
    public void setAsignacionPantallas(Set asignacionPantallas) {
        this.asignacionPantallas = asignacionPantallas;
    }




}


