package ec.tienda.movil.usuario.modelo;
// Generated 09/11/2017 16:19:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Perfil generated by hbm2java
 */
@XmlRootElement
public class Perfil implements java.io.Serializable {

    private Integer idPerfil;
    private String perfil;
    private Set asignacionPerfils = new HashSet(0);
    private Set asignacionPantallas = new HashSet(0);

    public Perfil() {
    }

    public Perfil(String perfil) {
        this.perfil = perfil;
    }

    public Perfil(String perfil, Set asignacionPerfils, Set asignacionPantallas) {
        this.perfil = perfil;
        this.asignacionPerfils = asignacionPerfils;
        this.asignacionPantallas = asignacionPantallas;
    }

    public Integer getIdPerfil() {
        return this.idPerfil;
    }

    public void setIdPerfil(Integer idPerfil) {
        this.idPerfil = idPerfil;
    }

    public String getPerfil() {
        return this.perfil;
    }

    public void setPerfil(String perfil) {
        this.perfil = perfil;
    }

    public Set getAsignacionPerfils() {
        return this.asignacionPerfils;
    }

    public void setAsignacionPerfils(Set asignacionPerfils) {
        this.asignacionPerfils = asignacionPerfils;
    }

    public Set getAsignacionPantallas() {
        return this.asignacionPantallas;
    }

    public void setAsignacionPantallas(Set asignacionPantallas) {
        this.asignacionPantallas = asignacionPantallas;
    }

}
