package ec.tienda.movil.usuario.modelo;
// Generated 09/11/2017 16:19:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sector generated by hbm2java
 */
public class Sector  implements java.io.Serializable {


     private Integer idSector;
     private String nombreSector;
     private Set ubicacions = new HashSet(0);

    public Sector() {
    }

    public Sector(String nombreSector, Set ubicacions) {
       this.nombreSector = nombreSector;
       this.ubicacions = ubicacions;
    }
   
    public Integer getIdSector() {
        return this.idSector;
    }
    
    public void setIdSector(Integer idSector) {
        this.idSector = idSector;
    }
    public String getNombreSector() {
        return this.nombreSector;
    }
    
    public void setNombreSector(String nombreSector) {
        this.nombreSector = nombreSector;
    }
    public Set getUbicacions() {
        return this.ubicacions;
    }
    
    public void setUbicacions(Set ubicacions) {
        this.ubicacions = ubicacions;
    }




}


