package ec.tienda.movil.usuario.modelo;
// Generated 09/11/2017 16:19:18 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * TipoUsuario generated by hbm2java
 */
@XmlRootElement
public class TipoUsuario implements java.io.Serializable {

    private Integer idTipoUsuario;
    private String tipoUsuario;
    private Set datosUsuarios = new HashSet(0);

    public TipoUsuario() {
    }

    public TipoUsuario(String tipoUsuario, Set datosUsuarios) {
        this.tipoUsuario = tipoUsuario;
        this.datosUsuarios = datosUsuarios;
    }

    public Integer getIdTipoUsuario() {
        return this.idTipoUsuario;
    }

    public void setIdTipoUsuario(Integer idTipoUsuario) {
        this.idTipoUsuario = idTipoUsuario;
    }

    public String getTipoUsuario() {
        return this.tipoUsuario;
    }

    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }

    public Set getDatosUsuarios() {
        return this.datosUsuarios;
    }

    public void setDatosUsuarios(Set datosUsuarios) {
        this.datosUsuarios = datosUsuarios;
    }

}
