package ec.tienda.movil.usuario.modelo;
// Generated 09/11/2017 16:19:18 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoAcceso generated by hbm2java
 */
public class TipoAcceso  implements java.io.Serializable {


     private Integer idTipoAcceso;
     private String tipoAcceso;
     private Set datosUsuarios = new HashSet(0);

    public TipoAcceso() {
    }

    public TipoAcceso(String tipoAcceso, Set datosUsuarios) {
       this.tipoAcceso = tipoAcceso;
       this.datosUsuarios = datosUsuarios;
    }
   
    public Integer getIdTipoAcceso() {
        return this.idTipoAcceso;
    }
    
    public void setIdTipoAcceso(Integer idTipoAcceso) {
        this.idTipoAcceso = idTipoAcceso;
    }
    public String getTipoAcceso() {
        return this.tipoAcceso;
    }
    
    public void setTipoAcceso(String tipoAcceso) {
        this.tipoAcceso = tipoAcceso;
    }
    public Set getDatosUsuarios() {
        return this.datosUsuarios;
    }
    
    public void setDatosUsuarios(Set datosUsuarios) {
        this.datosUsuarios = datosUsuarios;
    }




}


