package ec.tienda.movil.financiero.modelo;
// Generated 09/11/2017 16:36:03 by Hibernate Tools 4.3.1



/**
 * DineroElectronico generated by hbm2java
 */
public class DineroElectronico  implements java.io.Serializable {


     private int idDineroElectronico;
     private String identificadorDe;
     private String valorCambioDe;

    public DineroElectronico() {
    }

	
    public DineroElectronico(int idDineroElectronico, String identificadorDe) {
        this.idDineroElectronico = idDineroElectronico;
        this.identificadorDe = identificadorDe;
    }
    public DineroElectronico(int idDineroElectronico, String identificadorDe, String valorCambioDe) {
       this.idDineroElectronico = idDineroElectronico;
       this.identificadorDe = identificadorDe;
       this.valorCambioDe = valorCambioDe;
    }
   
    public int getIdDineroElectronico() {
        return this.idDineroElectronico;
    }
    
    public void setIdDineroElectronico(int idDineroElectronico) {
        this.idDineroElectronico = idDineroElectronico;
    }
    public String getIdentificadorDe() {
        return this.identificadorDe;
    }
    
    public void setIdentificadorDe(String identificadorDe) {
        this.identificadorDe = identificadorDe;
    }
    public String getValorCambioDe() {
        return this.valorCambioDe;
    }
    
    public void setValorCambioDe(String valorCambioDe) {
        this.valorCambioDe = valorCambioDe;
    }




}


