package ec.tienda.movil.financiero.modelo;
// Generated 09/11/2017 16:36:03 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Fecha generated by hbm2java
 */
public class Fecha implements java.io.Serializable {

    private Integer idFecha;
    private Hora hora;
    private Date fechaEntrega;
    private String estadoFecha;
    private Set horarios = new HashSet(0);

    public Fecha() {
    }

    public Fecha(Hora hora) {
        this.hora = hora;
    }

    public Fecha(Hora hora, Date fechaEntrega, String estadoFecha, Set horarios) {
        this.hora = hora;
        this.fechaEntrega = fechaEntrega;
        this.estadoFecha = estadoFecha;
        this.horarios = horarios;
    }

    public Integer getIdFecha() {
        return this.idFecha;
    }

    public void setIdFecha(Integer idFecha) {
        this.idFecha = idFecha;
    }

    public Hora getHora() {
        return this.hora;
    }

    public void setHora(Hora hora) {
        this.hora = hora;
    }

    public Date getFechaEntrega() {
        return this.fechaEntrega;
    }

    public void setFechaEntrega(Date fechaEntrega) {
        this.fechaEntrega = fechaEntrega;
    }

    public String getEstadoFecha() {
        return this.estadoFecha;
    }

    public void setEstadoFecha(String estadoFecha) {
        this.estadoFecha = estadoFecha;
    }

    public Set getHorarios() {
        return this.horarios;
    }

    public void setHorarios(Set horarios) {
        this.horarios = horarios;
    }

}
