package ec.tienda.movil.financiero.modelo;
// Generated 09/11/2017 16:36:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FormaPago generated by hbm2java
 */
public class FormaPago  implements java.io.Serializable {


     private Integer idFormaPago;
     private Integer tipoPago;
     private String numeroPago;
     private Set ventas = new HashSet(0);

    public FormaPago() {
    }

    public FormaPago(Integer tipoPago, String numeroPago, Set ventas) {
       this.tipoPago = tipoPago;
       this.numeroPago = numeroPago;
       this.ventas = ventas;
    }
   
    public Integer getIdFormaPago() {
        return this.idFormaPago;
    }
    
    public void setIdFormaPago(Integer idFormaPago) {
        this.idFormaPago = idFormaPago;
    }
    public Integer getTipoPago() {
        return this.tipoPago;
    }
    
    public void setTipoPago(Integer tipoPago) {
        this.tipoPago = tipoPago;
    }
    public String getNumeroPago() {
        return this.numeroPago;
    }
    
    public void setNumeroPago(String numeroPago) {
        this.numeroPago = numeroPago;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


