package ec.tienda.movil.financiero.modelo;
// Generated 09/11/2017 16:36:03 by Hibernate Tools 4.3.1

import javax.xml.bind.annotation.XmlRootElement;

/**
 * Horario generated by hbm2java
 */
@XmlRootElement
public class Horario implements java.io.Serializable {

    private Integer idHorario;
    private Fecha fecha;
    private Venta venta;
    private String disponibilidad;
    private String precioEntrega;

    public Horario() {
    }

    public Horario(Fecha fecha, Venta venta) {
        this.fecha = fecha;
        this.venta = venta;
    }

    public Horario(Fecha fecha, Venta venta, String disponibilidad, String precioEntrega) {
        this.fecha = fecha;
        this.venta = venta;
        this.disponibilidad = disponibilidad;
        this.precioEntrega = precioEntrega;
    }

    public Integer getIdHorario() {
        return this.idHorario;
    }

    public void setIdHorario(Integer idHorario) {
        this.idHorario = idHorario;
    }

    public Fecha getFecha() {
        return this.fecha;
    }

    public void setFecha(Fecha fecha) {
        this.fecha = fecha;
    }

    public Venta getVenta() {
        return this.venta;
    }

    public void setVenta(Venta venta) {
        this.venta = venta;
    }

    public String getDisponibilidad() {
        return this.disponibilidad;
    }

    public void setDisponibilidad(String disponibilidad) {
        this.disponibilidad = disponibilidad;
    }

    public String getPrecioEntrega() {
        return this.precioEntrega;
    }

    public void setPrecioEntrega(String precioEntrega) {
        this.precioEntrega = precioEntrega;
    }

}
