package ec.tienda.movil.financiero.modelo;
// Generated 09/11/2017 16:36:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Hora generated by hbm2java
 */
public class Hora  implements java.io.Serializable {


     private Integer idHora;
     private String horaEntrega1;
     private String horaEntrega2;
     private String estadoHora;
     private Set fechas = new HashSet(0);

    public Hora() {
    }

    public Hora(String horaEntrega1, String horaEntrega2, String estadoHora, Set fechas) {
       this.horaEntrega1 = horaEntrega1;
       this.horaEntrega2 = horaEntrega2;
       this.estadoHora = estadoHora;
       this.fechas = fechas;
    }
   
    public Integer getIdHora() {
        return this.idHora;
    }
    
    public void setIdHora(Integer idHora) {
        this.idHora = idHora;
    }
    public String getHoraEntrega1() {
        return this.horaEntrega1;
    }
    
    public void setHoraEntrega1(String horaEntrega1) {
        this.horaEntrega1 = horaEntrega1;
    }
    public String getHoraEntrega2() {
        return this.horaEntrega2;
    }
    
    public void setHoraEntrega2(String horaEntrega2) {
        this.horaEntrega2 = horaEntrega2;
    }
    public String getEstadoHora() {
        return this.estadoHora;
    }
    
    public void setEstadoHora(String estadoHora) {
        this.estadoHora = estadoHora;
    }
    public Set getFechas() {
        return this.fechas;
    }
    
    public void setFechas(Set fechas) {
        this.fechas = fechas;
    }




}


