package ec.tienda.movil.financiero.modelo;
// Generated 09/11/2017 16:36:03 by Hibernate Tools 4.3.1

/**
 * Paypal generated by hbm2java
 */
public class Paypal implements java.io.Serializable {

    private Integer idPaypal;
    private String numeroTarjeta;
    private String identificadorPaypal;

    public Paypal() {
    }

    public Paypal(String numeroTarjeta) {
        this.numeroTarjeta = numeroTarjeta;
    }

    public Paypal(String numeroTarjeta, String identificadorPaypal) {
        this.numeroTarjeta = numeroTarjeta;
        this.identificadorPaypal = identificadorPaypal;
    }

    public Integer getIdPaypal() {
        return this.idPaypal;
    }

    public void setIdPaypal(Integer idPaypal) {
        this.idPaypal = idPaypal;
    }

    public String getNumeroTarjeta() {
        return this.numeroTarjeta;
    }

    public void setNumeroTarjeta(String numeroTarjeta) {
        this.numeroTarjeta = numeroTarjeta;
    }

    public String getIdentificadorPaypal() {
        return this.identificadorPaypal;
    }

    public void setIdentificadorPaypal(String identificadorPaypal) {
        this.identificadorPaypal = identificadorPaypal;
    }

}
