package ec.tienda.movil.financiero.modelo;
// Generated 09/11/2017 16:36:03 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * SalidaPago generated by hbm2java
 */
public class SalidaPago implements java.io.Serializable {

    private Integer idSalidaPago;
    private Integer idSalidaP;
    private Set ventas = new HashSet(0);

    public SalidaPago() {
    }

    public SalidaPago(Integer idSalidaP, Set ventas) {
        this.idSalidaP = idSalidaP;
        this.ventas = ventas;
    }

    public Integer getIdSalidaPago() {
        return this.idSalidaPago;
    }

    public void setIdSalidaPago(Integer idSalidaPago) {
        this.idSalidaPago = idSalidaPago;
    }

    public Integer getIdSalidaP() {
        return this.idSalidaP;
    }

    public void setIdSalidaP(Integer idSalidaP) {
        this.idSalidaP = idSalidaP;
    }

    public Set getVentas() {
        return this.ventas;
    }

    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }

}
