package ec.tienda.movil.financiero.modelo;
// Generated 09/11/2017 16:36:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venta generated by hbm2java
 */
public class Venta  implements java.io.Serializable {


     private Integer idVenta;
     private ClientePago clientePago;
     private FormaPago formaPago;
     private SalidaPago salidaPago;
     private String subtotal;
     private String iva;
     private String total;
     private Date fechaVenta;
     private String codigoVenta;
     private String valorCambio;
     private Set horarios = new HashSet(0);

    public Venta() {
    }

	
    public Venta(ClientePago clientePago, FormaPago formaPago, SalidaPago salidaPago) {
        this.clientePago = clientePago;
        this.formaPago = formaPago;
        this.salidaPago = salidaPago;
    }
    public Venta(ClientePago clientePago, FormaPago formaPago, SalidaPago salidaPago, String subtotal, String iva, String total, Date fechaVenta, String codigoVenta, String valorCambio, Set horarios) {
       this.clientePago = clientePago;
       this.formaPago = formaPago;
       this.salidaPago = salidaPago;
       this.subtotal = subtotal;
       this.iva = iva;
       this.total = total;
       this.fechaVenta = fechaVenta;
       this.codigoVenta = codigoVenta;
       this.valorCambio = valorCambio;
       this.horarios = horarios;
    }
   
    public Integer getIdVenta() {
        return this.idVenta;
    }
    
    public void setIdVenta(Integer idVenta) {
        this.idVenta = idVenta;
    }
    public ClientePago getClientePago() {
        return this.clientePago;
    }
    
    public void setClientePago(ClientePago clientePago) {
        this.clientePago = clientePago;
    }
    public FormaPago getFormaPago() {
        return this.formaPago;
    }
    
    public void setFormaPago(FormaPago formaPago) {
        this.formaPago = formaPago;
    }
    public SalidaPago getSalidaPago() {
        return this.salidaPago;
    }
    
    public void setSalidaPago(SalidaPago salidaPago) {
        this.salidaPago = salidaPago;
    }
    public String getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(String subtotal) {
        this.subtotal = subtotal;
    }
    public String getIva() {
        return this.iva;
    }
    
    public void setIva(String iva) {
        this.iva = iva;
    }
    public String getTotal() {
        return this.total;
    }
    
    public void setTotal(String total) {
        this.total = total;
    }
    public Date getFechaVenta() {
        return this.fechaVenta;
    }
    
    public void setFechaVenta(Date fechaVenta) {
        this.fechaVenta = fechaVenta;
    }
    public String getCodigoVenta() {
        return this.codigoVenta;
    }
    
    public void setCodigoVenta(String codigoVenta) {
        this.codigoVenta = codigoVenta;
    }
    public String getValorCambio() {
        return this.valorCambio;
    }
    
    public void setValorCambio(String valorCambio) {
        this.valorCambio = valorCambio;
    }
    public Set getHorarios() {
        return this.horarios;
    }
    
    public void setHorarios(Set horarios) {
        this.horarios = horarios;
    }




}


